# Generated by Django 5.1.3 on 2024-11-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='request_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
